# Generated by Django 3.2.19 on 2023-05-14 17:43

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='images', verbose_name='Imagen'),
        ),
    ]
